name: Deploy npm

on:
    push:
        branches:
            - master

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
         - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
        - name: Checkout Code
          uses: actions/checkout@v2
          with:
              ref: ${{ github.ref }}
        - name: Install prerequisites
          run: npm install -g yarn
        - name: Install dependencies
          run: yarn
        - name: Install dependencies
          run: yarn build
        - name: Semantic Release
          uses: cycjimmy/semantic-release-action@v2
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
